#pragma once

#include <cstdint>
#include <string>
#include <vector>

#include "care_daily/routine_id.h"

namespace xiaozhi_care::daily {

/**
 * @brief Conversational state of an activity being accompanied by CARE.
 *
 * These states describe the temporary activity of the day.
 * They are deliberately separate from RoutineExecution.
 */
enum class CompanionActivityState : uint8_t {
    Discover,
    Recall,
    CheckResources,
    Organize,
    Doing,
    Deferred,
    Completed,
    Cancelled,
    Unknown,
};

/**
 * @brief Amount of help CARE is currently providing.
 *
 * 0: the person recalls independently
 * 1: open question
 * 2: small hint
 * 3: concrete help
 */
enum class CompanionHelpLevel : uint8_t {
    Independent = 0,
    OpenQuestion = 1,
    Hint = 2,
    ConcreteHelp = 3,
};

/**
 * @brief Provenance of a fact stored in day memory.
 *
 * A CARE suggestion must never silently become a user-confirmed fact.
 */
enum class DayMemoryFactSource : uint8_t {
    UserRecalled,
    UserConfirmed,
    CareSuggested,
};

/**
 * @brief One temporary fact remembered during an activity.
 */
struct DayActivityFact {
    std::string value;
    DayMemoryFactSource source{DayMemoryFactSource::UserRecalled};

    [[nodiscard]] bool IsValid() const {
        return !value.empty();
    }
};

/**
 * @brief Short-lived memory used while CARE accompanies a daily activity.
 *
 * This is not permanent personal memory and it is not an execution record.
 *
 * Examples:
 * - preparing dinner
 * - getting ready to go out
 * - painting
 * - watering plants
 * - preparing for an appointment
 *
 * routine_id is optional because not every accompanied activity must come
 * from a registered CareRoutine.
 */
struct DayActivityMemory {
    // Opaque identifier generated by the day-memory repository.
    // It is independent from routine_id because an accompanied activity
    // does not necessarily originate from a registered CareRoutine.
    std::string memory_id;

    std::string iso_date;
    std::string activity;

    RoutineId routine_id;

    CompanionActivityState state{CompanionActivityState::Discover};
    CompanionHelpLevel help_level{CompanionHelpLevel::Independent};

    DayActivityFact plan;
    DayActivityFact current_step;

    std::vector<DayActivityFact> recalled_steps;
    std::vector<DayActivityFact> available_items;
    std::vector<DayActivityFact> missing_items;

    bool reminder_created{false};
    std::string reminder_text;

    /**
     * Unix timestamps in seconds.
     *
     * Zero means that the value is not known / not set.
     */
    int64_t last_interaction_unix{0};
    int64_t defer_until_unix{0};

    [[nodiscard]] bool IsValidDate() const {
        return iso_date.size() == 10 &&
               iso_date[4] == '-' &&
               iso_date[7] == '-';
    }

    [[nodiscard]] bool IsValid() const {
        return !memory_id.empty() &&
               IsValidDate() &&
               !activity.empty();
    }
};

const char* CompanionActivityStateName(CompanionActivityState state);
const char* CompanionHelpLevelName(CompanionHelpLevel level);
const char* DayMemoryFactSourceName(DayMemoryFactSource source);

}  // namespace xiaozhi_care::daily